# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set MACOSX_DEPLOYMENT_TARGET
        if: runner.os == 'macOS'
        run: |
          echo 'MACOSX_DEPLOYMENT_TARGET=14.0' >> $GITHUB_ENV
          
      - name: Build luajit and luarocks
        run: |
          MACOSX_DEPLOYMENT_TARGET=14.0 python ./hererocks/hererocks.py x86_64_dir -jlatest -rlatest --verbose
          ./x86_64_dir/bin/luarocks install inspect
          ./x86_64_dir/bin/luarocks install luaposix
          ./x86_64_dir/bin/luarocks install luasocket
          ./x86_64_dir/bin/luarocks install rxi-json-lua

      - name: Install libgl
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install libgl-dev
          
      - name: Install SDL2
        run: |
          cd LuaJIT-SDL2/SDL &&
          cmake -Bbuild 
          cmake --build build --parallel $(nproc)
          sudo cmake --build build --parallel $(nproc) --target install
          
      - name: Build imgui for luajit
        run: |
          bash build_imgui.sh ./x86_64_dir

      - name: Compress install dir
        run: |
          tar -C ./x86_64_dir -czvf x86_64_dir.tar.gz .

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64_dir.tar.gz
          path: ./x86_64_dir.tar.gz

      - uses: actions/upload-artifact@v4
        with:
          name: x86_64_dir
          path: ./x86_64_dir/
